### Assignment 1 Sample Codes

In [10]:
# Import modules
import pandas as pd
import numpy as np
import csv

#### Question 1

In [4]:
# import monthly data
monthly = pd.read_csv('./monthly.csv',header=None)
date = monthly.iloc[:,0]
monthly = monthly.drop(0,axis=1)
monthly.columns = ['VW','EW']+['DEC{}'.format(i) for i in range(1, 11)]  # Specify the names of the columns

### Here is the code for generating some test statistics for the portfolios

In [5]:
monthly.describe()

VW           EW         DEC1         DEC2         DEC3  \
count  1128.000000  1128.000000  1128.000000  1128.000000  1128.000000   
mean      0.009259     0.012221     0.017078     0.013232     0.011625   
std       0.053128     0.071512     0.102692     0.088211     0.079402   
min      -0.291731    -0.312753    -0.350205    -0.357532    -0.325695   
25%      -0.018074    -0.019978    -0.029277    -0.025744    -0.022344   
50%       0.012866     0.014240     0.009539     0.011423     0.011212   
75%       0.038917     0.043249     0.053191     0.046167     0.045907   
max       0.394143     0.665936     1.112312     0.865855     0.894700   

              DEC4         DEC5         DEC6         DEC7         DEC8  \
count  1128.000000  1128.000000  1128.000000  1128.000000  1128.000000   
mean      0.011314     0.011257     0.011053     0.010901     0.010030   
std       0.074804     0.071765     0.069471     0.066436     0.062544   
min      -0.319836    -0.333994    -0.323497    -0.299028    -0.325057   
25%      -0.023339    -0.022033    -0.022264    -0.022383    -0.021748   
50%       0.013363     0.012711     0.014455     0.014134     0.013647   
75%       0.045745     0.044651     0.045492     0.045494     0.043670   
max       0.641794     0.605076     0.537786     0.538020     0.514179   

              DEC9        DEC10  
count  1128.000000  1128.000000  
mean      0.010473     0.008894  
std       0.059232     0.050877  
min      -0.314467    -0.281972  
25%      -0.019158    -0.016667  
50%       0.014152     0.012309  
75%       0.043093     0.038145  
max       0.439538     0.365025

In [8]:
#Skewness and kurtosis test

In [33]:
from scipy.stats import kurtosis, skew, normaltest
skew(monthly)

array([0.14871698, 1.49791109, 3.03379398, 2.04901595, 1.94986295,
       1.12841379, 0.9070566 , 0.66628446, 0.46853841, 0.30422241,
       0.22340303, 0.08464521])

In [34]:
kurtosis(monthly)

array([ 7.96824207, 15.30637496, 25.45470337, 19.01234216, 21.52575842,
       12.10151984, 11.29743462,  9.24767615,  8.18678295,  8.30033828,
        7.86479231,  7.41407592])

In [11]:
#Normality test

In [12]:
normaltest(skew(monthly))

C:\Users\16138\anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


NormaltestResult(statistic=2.545730502542165, pvalue=0.28002812028366514)

In [13]:
normaltest(kurtosis(monthly))

NormaltestResult(statistic=2.9605828299041623, pvalue=0.22757136102262226)

In [14]:
#Conclusion: the distribution is not normal- the p value is much higher than 0, thus the result is not statistically significant. 
#cannot reject the null hypothesis- that the distribution is normal

In [29]:
#question3-summary statistics for january
jan=pd.read_csv("./monthly.csv",header=None)
df_jan=jan.rename(columns={0:"date"})
january=df_jan.loc[::12,:]
print(january)



          date         1         2         3         4         5         6  \
0     19260130  0.000561  0.023174  0.143660  0.043982  0.003839  0.021334   
12    19270131  0.002416  0.012556  0.003172  0.002805  0.014317  0.032929   
24    19280131 -0.003340  0.032441  0.082891  0.036933  0.050425  0.024538   
36    19290131  0.053935  0.033526  0.037070  0.014078  0.026836  0.018479   
48    19300131  0.058407  0.109826  0.240036  0.167626  0.119548  0.166176   
...        ...       ...       ...       ...       ...       ...       ...   
1068  20150130 -0.028451 -0.021522  0.001871  0.004039 -0.012599 -0.042065   
1080  20160129 -0.058119 -0.082914 -0.077448 -0.083936 -0.088380 -0.084737   
1092  20170131  0.022354  0.027060  0.069403  0.034900  0.028130  0.009595   
1104  20180131  0.051369  0.029025  0.035603  0.022869  0.029548  0.006349   
1116  20190131  0.089323  0.133112  0.257212  0.156958  0.121558  0.094528   

             7         8         9        10        11        1

In [30]:
jan_df=january.drop("date",axis=1)
jan_df.columns=["VW","EW"]+["Dec{}".format(i) for i in range(1,11)] #labelling columns
print(jan_df)

            VW        EW      Dec1      Dec2      Dec3      Dec4      Dec5  \
0     0.000561  0.023174  0.143660  0.043982  0.003839  0.021334  0.026445   
12    0.002416  0.012556  0.003172  0.002805  0.014317  0.032929  0.016315   
24   -0.003340  0.032441  0.082891  0.036933  0.050425  0.024538  0.007223   
36    0.053935  0.033526  0.037070  0.014078  0.026836  0.018479  0.013253   
48    0.058407  0.109826  0.240036  0.167626  0.119548  0.166176  0.073301   
...        ...       ...       ...       ...       ...       ...       ...   
1068 -0.028451 -0.021522  0.001871  0.004039 -0.012599 -0.042065 -0.038437   
1080 -0.058119 -0.082914 -0.077448 -0.083936 -0.088380 -0.084737 -0.091393   
1092  0.022354  0.027060  0.069403  0.034900  0.028130  0.009595  0.004011   
1104  0.051369  0.029025  0.035603  0.022869  0.029548  0.006349  0.008132   
1116  0.089323  0.133112  0.257212  0.156958  0.121558  0.094528  0.138760   

          Dec6      Dec7      Dec8      Dec9     Dec10  
0    -

In [31]:
#jan summary statistics
jan_df.describe()

VW         EW       Dec1       Dec2       Dec3       Dec4  \
count  94.000000  94.000000  94.000000  94.000000  94.000000  94.000000   
mean    0.015453   0.053160   0.124780   0.084924   0.068584   0.056921   
std     0.047539   0.070806   0.124875   0.092798   0.083173   0.078740   
min    -0.077467  -0.082914  -0.077448  -0.089692  -0.088380  -0.103138   
25%    -0.025711   0.005728   0.044327   0.023751   0.016708   0.008303   
50%     0.015043   0.040897   0.087863   0.062954   0.057791   0.042505   
75%     0.050925   0.088335   0.155497   0.116180   0.100781   0.091929   
max     0.141600   0.315546   0.638277   0.455985   0.430647   0.355285   

            Dec5       Dec6       Dec7       Dec8       Dec9      Dec10  
count  94.000000  94.000000  94.000000  94.000000  94.000000  94.000000  
mean    0.047137   0.041591   0.032557   0.025499   0.022475   0.010856  
std     0.070693   0.070380   0.065302   0.059004   0.054192   0.045922  
min    -0.091393  -0.096984  -0.092163  -0.090376  -0.081609  -0.079495  
25%     0.004423  -0.006743  -0.008638  -0.017942  -0.014710  -0.024173  
50%     0.040299   0.038484   0.022298   0.017866   0.021609   0.010849  
75%     0.081865   0.085758   0.074387   0.066524   0.056763   0.044261  
max     0.321189   0.295842   0.281120   0.250274   0.226106   0.131437

In [35]:
#skewness test for jan
from scipy.stats import kurtosis, skew, normaltest
skew(jan_df)

array([0.25555579, 1.09454683, 1.65806033, 1.30772427, 1.41517651,
       1.30625508, 1.04104372, 0.98981015, 1.07494643, 0.67108662,
       0.68002966, 0.16333556])

In [36]:
#kurtosis test for jan
kurtosis(jan_df)

array([-0.14669631,  2.1363484 ,  3.39866926,  2.37379855,  3.56913414,
        3.04611249,  2.09185022,  2.06214406,  2.46447369,  1.257866  ,
        1.26264871, -0.32938895])

In [37]:
#normality test
normaltest(skew(jan_df))

C:\Users\16138\anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


NormaltestResult(statistic=0.7641060730338008, pvalue=0.682458857004835)

In [38]:
normaltest(kurtosis(jan_df))

NormaltestResult(statistic=1.2205968697368563, pvalue=0.5431887384233003)

In [ ]:
#as a result the distribution is not normal- the large p-value means we cannot reject the null hypothesis (normality)

In [40]:
#REST OF MONTHS
months=df_jan[df_jan.index % 12 !=0]
print(months)

          date         1         2         3         4         5         6  \
1     19260227 -0.033046 -0.053510 -0.045718 -0.067602 -0.045779 -0.079699   
2     19260331 -0.064002 -0.096824 -0.139863 -0.095192 -0.125909 -0.116952   
3     19260430  0.037019  0.032946  0.046633  0.011215  0.010318  0.055662   
4     19260528  0.012095  0.001035 -0.004305 -0.021611  0.002612  0.023445   
5     19260630  0.053664  0.050487  0.001354  0.048366  0.063170  0.036993   
...        ...       ...       ...       ...       ...       ...       ...   
1123  20190830 -0.020776 -0.045753 -0.050496 -0.037699 -0.028386 -0.044906   
1124  20190930  0.016057  0.018962 -0.024063 -0.007751  0.009949  0.019673   
1125  20191031  0.019245  0.003973 -0.039683 -0.027228  0.006116  0.006034   
1126  20191129  0.036100  0.029982 -0.009684  0.035877  0.047326  0.038627   
1127  20191231  0.028380  0.048576  0.051570  0.098430  0.063607  0.050885   

             7         8         9        10        11        1

In [41]:
month_df=months.drop("date", axis=1)
month_df.columns=["VW","EW"]+["Dec{}".format(i) for i in range (1,11)] #labelling columns
print(month_df)

            VW        EW      Dec1      Dec2      Dec3      Dec4      Dec5  \
1    -0.033046 -0.053510 -0.045718 -0.067602 -0.045779 -0.079699 -0.070859   
2    -0.064002 -0.096824 -0.139863 -0.095192 -0.125909 -0.116952 -0.093662   
3     0.037019  0.032946  0.046633  0.011215  0.010318  0.055662  0.062817   
4     0.012095  0.001035 -0.004305 -0.021611  0.002612  0.023445  0.009262   
5     0.053664  0.050487  0.001354  0.048366  0.063170  0.036993  0.037166   
...        ...       ...       ...       ...       ...       ...       ...   
1123 -0.020776 -0.045753 -0.050496 -0.037699 -0.028386 -0.044906 -0.053701   
1124  0.016057  0.018962 -0.024063 -0.007751  0.009949  0.019673  0.011758   
1125  0.019245  0.003973 -0.039683 -0.027228  0.006116  0.006034  0.017182   
1126  0.036100  0.029982 -0.009684  0.035877  0.047326  0.038627  0.036025   
1127  0.028380  0.048576  0.051570  0.098430  0.063607  0.050885  0.044401   

          Dec6      Dec7      Dec8      Dec9     Dec10  
1    -

In [42]:
#summary statistics 
month_df.describe()

VW           EW         Dec1         Dec2         Dec3  \
count  1034.000000  1034.000000  1034.000000  1034.000000  1034.000000   
mean      0.008696     0.008500     0.007287     0.006715     0.006447   
std       0.053592     0.070439     0.094603     0.084874     0.077030   
min      -0.291731    -0.312753    -0.350205    -0.357532    -0.325695   
25%      -0.017685    -0.022503    -0.033722    -0.029557    -0.025328   
50%       0.012761     0.012029     0.005498     0.008656     0.008357   
75%       0.037924     0.041073     0.041991     0.040795     0.040907   
max       0.394143     0.665936     1.112312     0.865855     0.894700   

              Dec4         Dec5         Dec6         Dec7         Dec8  \
count  1034.000000  1034.000000  1034.000000  1034.000000  1034.000000   
mean      0.007168     0.007995     0.008277     0.008933     0.008624   
std       0.073076     0.071001     0.068752     0.066219     0.062694   
min      -0.319836    -0.333994    -0.323497    -0.299028    -0.325057   
25%      -0.026420    -0.023924    -0.023391    -0.023317    -0.021955   
50%       0.010515     0.011303     0.011823     0.013502     0.013141   
75%       0.041977     0.041774     0.043308     0.043627     0.041714   
max       0.641794     0.605076     0.537786     0.538020     0.514179   

              Dec9        Dec10  
count  1034.000000  1034.000000  
mean      0.009382     0.008716  
std       0.059574     0.051321  
min      -0.314467    -0.281972  
25%      -0.019282    -0.016150  
50%       0.013789     0.012460  
75%       0.041953     0.037571  
max       0.439538     0.365025

In [44]:
#skewness test
skew(month_df)


array([0.14891605, 1.59270498, 3.53338998, 2.25975384, 2.10277652,
       1.12668144, 0.9207269 , 0.642364  , 0.42401924, 0.28633548,
       0.2029006 , 0.08164921])

In [45]:
#kurtosis test
kurtosis(month_df)

array([ 8.39272066, 17.64527652, 36.8413594 , 23.97116306, 26.11031214,
       13.97717454, 12.66349972, 10.24485514,  8.77295745,  8.85801352,
        8.28229119,  7.8212698 ])

In [47]:
#normal test
normaltest(skew(month_df))

C:\Users\16138\anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


NormaltestResult(statistic=4.028935239455341, pvalue=0.13339139941537165)

In [48]:
#normal test
normaltest(kurtosis(month_df))

NormaltestResult(statistic=6.087527035952243, pvalue=0.04765520037141705)

In [ ]:
#the normal test results are vastly different when january is removed from the equation
#when doing the normal test for skewness still has a high p-value- not normal
#normal test for kurtosis- small p-value, distribution is normal

#### Question 2

In [16]:
#import datetime

In [92]:
# Input the data
daily = pd.read_csv('./daily.csv',header=None)

# change column names
daily.columns = ['date', 'value-weighted', 'equal-weighted']

# convert date into datetime object 
daily['date'] = pd.to_datetime(daily['date'], format='%Y%m%d') # http://strftime.org/

### create variable weekday that represents the day in the date column 
### (NOTE: python count starts at 0)
weekday = daily['date'].dt.dayofweek
week_label = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']



In [53]:
#computing summmary statistics for the data
daily.describe()

value-weighted  equal-weighted
count    24792.000000    24792.000000
mean         0.000412        0.000829
std          0.010568        0.010472
min         -0.171349       -0.135467
25%         -0.003800       -0.002906
50%          0.000746        0.001307
75%          0.005005        0.005012
max          0.156838        0.203020

In [19]:
#calculating skewness
skew(daily)

array([ 0.06789623, -0.13039151,  0.32294331])

In [20]:
#calulcating kurtosis
kurtosis(daily)

array([-1.23653561, 16.72439458, 25.79055918])

In [95]:
#normal test- using scipy does not work as there is less than 8 samples
#kutosis should be around 0:
for v in kurtosis(daily):
    print(0-v)
#distribution is not normal


1.2365356115751833
-16.724394577986818
-25.79055918246586


In [96]:
#skewness should be around 0 
for v in skew(daily):
    print(0-v)
#values approach 0 but not enough to be normal

-0.06789623016246438
0.13039151302383362
-0.32294330880668204


In [58]:
#look on splitting data again
newdaily=pd.read_csv("./daily.csv",header=None)
sat_rows=newdaily.loc[::6,:]
print(sat_rows)

              0         1         2
0      19260102  0.005689  0.009516
6      19260109  0.002209  0.003312
12     19260116 -0.001224 -0.001544
18     19260123  0.005657  0.006987
24     19260130  0.000687  0.004532
...         ...       ...       ...
24762  20191118  0.000150 -0.003681
24768  20191126  0.002265  0.000353
24774  20191205  0.001087 -0.000769
24780  20191213 -0.000017 -0.001026
24786  20191223  0.000947  0.004648

[4132 rows x 3 columns]


In [60]:
sat_df=sat_rows.drop(0,axis=1)
print(sat_df)


              1         2
0      0.005689  0.009516
6      0.002209  0.003312
12    -0.001224 -0.001544
18     0.005657  0.006987
24     0.000687  0.004532
...         ...       ...
24762  0.000150 -0.003681
24768  0.002265  0.000353
24774  0.001087 -0.000769
24780 -0.000017 -0.001026
24786  0.000947  0.004648

[4132 rows x 2 columns]


In [61]:
#summary statistics for saturday
sat_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000466     0.000867
std       0.010486     0.010313
min      -0.113021    -0.095202
25%      -0.003642    -0.002842
50%       0.000739     0.001354
75%       0.005123     0.005007
max       0.080367     0.124870

In [62]:
#skewness test
skew(sat_df)

array([-0.61126386, -0.03140307])

In [63]:
#kurtosis test
kurtosis(sat_df)

array([12.20783704, 16.14253474])

In [97]:
#normaltest
#skewness should be around 0 
for v in skew(sat_df):
    print(0-v)
#values approach 0 but not enough to be normal

0.6112638591373818
0.031403065378733906


In [98]:
#kurtosis should be around 0 
for v in kurtosis(sat_df):
    print(0-v)
#distribution is not normal

-12.207837039999125
-16.14253473748843


In [68]:
#summary statistics for monday
mon_rows=newdaily.loc[1::6,:]
mon_df=mon_rows.drop(0,axis=1)
mon_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000394     0.000740
std       0.010504     0.010343
min      -0.119539    -0.134856
25%      -0.003908    -0.003083
50%       0.000839     0.001287
75%       0.004951     0.005104
max       0.095421     0.104127

In [69]:
#skewness test
skew(mon_df)

array([-0.37782822, -0.83899788])

In [70]:
#kurtosis test 
kurtosis(mon_df)

array([13.40126046, 19.83258933])

In [100]:
#normal test
#skewness should be around 0 
for v in skew(mon_df):
    print(0-v)
#values approach 0 but not enough to be normal

0.37782821869175093
0.8389978803177551


In [101]:
#kurtosis should be around 0 
for v in kurtosis(mon_df):
    print(0-v)
#values are not normal ("fat" tail)

-13.401260461567396
-19.832589330264852


In [71]:
tue_rows=newdaily.loc[2::6,:]
tue_df=mon_rows.drop(0,axis=1)
tue_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000394     0.000740
std       0.010504     0.010343
min      -0.119539    -0.134856
25%      -0.003908    -0.003083
50%       0.000839     0.001287
75%       0.004951     0.005104
max       0.095421     0.104127

In [72]:
#skewness test
skew(tue_df)

array([-0.37782822, -0.83899788])

In [73]:
#kurtosis test
kurtosis(tue_df)

array([13.40126046, 19.83258933])

In [103]:
#normal test
#skewness should be around 0 
for v in skew(tue_df):
    print(0-v)
#values approach 0 but not enough to be normal

0.37782821869175093
0.8389978803177551


In [104]:
#kurtosis should be around 0 
for v in kurtosis(tue_df):
    print(0-v)
#values are not normal

-13.401260461567396
-19.832589330264852


In [81]:
wed_rows=newdaily.loc[3::6,:]
wed_df=mon_rows.drop(0,axis=1)
wed_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000394     0.000740
std       0.010504     0.010343
min      -0.119539    -0.134856
25%      -0.003908    -0.003083
50%       0.000839     0.001287
75%       0.004951     0.005104
max       0.095421     0.104127

In [82]:
#skewness
skew(wed_df)

array([-0.37782822, -0.83899788])

In [83]:
#kurtosis
kurtosis(wed_df)

array([13.40126046, 19.83258933])

In [106]:
#normal test
#skewness should be around 0 
for v in skew(wed_df):
    print(0-v)
#values are close to 0 not normal

0.37782821869175093
0.8389978803177551


In [107]:
#kurtosis should be around 0 
for v in kurtosis(wed_df):
    print(0-v)
#values are not normal

-13.401260461567396
-19.832589330264852


In [84]:
thurs_rows=newdaily.loc[4::6,:]
thurs_df=mon_rows.drop(0,axis=1)
thurs_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000394     0.000740
std       0.010504     0.010343
min      -0.119539    -0.134856
25%      -0.003908    -0.003083
50%       0.000839     0.001287
75%       0.004951     0.005104
max       0.095421     0.104127

In [85]:
#skewness
skew(thurs_df)

array([-0.37782822, -0.83899788])

In [86]:
#kurtosis
kurtosis(thurs_df)

array([13.40126046, 19.83258933])

In [109]:
#normal test
#skewness should be around 0 
for v in skew(thurs_df):
    print(0-v)
#values are not normal

0.37782821869175093
0.8389978803177551


In [110]:
#kurtosis should be around 0 
for v in kurtosis(thurs_df):
    print(0-v)
#values are not normal

-13.401260461567396
-19.832589330264852


In [87]:
fri_rows=newdaily.loc[5::6,:]
fri_df=mon_rows.drop(0,axis=1)
fri_df.describe()

1            2
count  4132.000000  4132.000000
mean      0.000394     0.000740
std       0.010504     0.010343
min      -0.119539    -0.134856
25%      -0.003908    -0.003083
50%       0.000839     0.001287
75%       0.004951     0.005104
max       0.095421     0.104127

In [88]:
#skewness
skew(fri_df)

array([-0.37782822, -0.83899788])

In [89]:
#kurtosis
kurtosis(fri_df)

array([13.40126046, 19.83258933])

In [112]:
#skewness should be around 0 
for v in skew(fri_df):
    print(0-v)
#values are close to normal

0.37782821869175093
0.8389978803177551


In [113]:
#kurtosis should be around 0 
for v in kurtosis(fri_df):
    print(0-v)
#values are not normal

-13.401260461567396
-19.832589330264852


In [ ]:
#normal test